add solution 5
Kotovar/ASTON_Solutions pull request #3
Opened 2024-04-04 10:16 UTC by Kotovar

Добавил решение 5го домашнего задания

2024-04-04 17:21 UTC, Kotovar commented
Добавил второе решение задачи

2024-04-05 09:10 UTC, ASTON-TRAINEE requested changes

2024-04-05 09:10 UTC, ASTON-TRAINEE commented on homework.js
> +// Bird.prototype.speak = Animal.prototype.speak;
это не корректно так передавать метод, нам нужно получить прототип всего Animal, а не только одного метода

2024-04-05 10:22 UTC, Kotovar commented on homework.js
> +// Bird.prototype.speak = Animal.prototype.speak;
@ASTON-TRAINEE Запушил новое решение

2024-04-05 10:24 UTC, ASTON-TRAINEE approved these changes
теперь все окей

2024-04-05 10:27 UTC, merged